#!/usr/bin/env bash
source $HOME/.bashrc $HOME/.profile

mkdir_fun(){
mkdir -p /root/export_tar_gz
}

pyenv_install(){
# 安装最新版 python 配置自定义虚拟环境
pyenv versions | sed 's;*;;g;s;/; ;g' | grep -oE ' 3(.){1,7}' | awk '{print $1}' | xargs pyenv uninstall -f
pyenv install -v `pyenv install --list | grep -oE ' 3(.){1,7}' | grep -v dev | tail -n -2 | head -n 1`
pyenv rehash
pyenv version
pyenv versions
}

tar_gz(){
cd $HOME
tar zcvf /root/export_tar_gz/pyenv.tar.gz .pyenv
echo 'ok done!'
}

mkdir_fun
pyenv_install
tar_gz
