# This is a basic workflow to help you get started with Actions

name: update pyenv and pyenv-virtualenv

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # Runs every 5 minutes.
  # Runs at 00:00 UTC every day.
  # Actions schedules run at most every 5 minutes.
  schedule:
    # - cron: '*/5 * * * *'
    - cron: '0 0 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: 迁出代码
        uses: actions/checkout@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # Runs a single command using the runners shell
      - name: Run install curl
        run: |
          sudo apt update
          sudo apt-get -y install curl
          
      # Runs a set of commands using the runners shell
      - name: Run update.sh shell script
        run: |
          chmod u+x update.sh
          bash update.sh
          
      - name: 'Get Date'
        run: |
          echo "REPORT_DATE=$(TZ=':Asia/Shanghai' date '+%Y-%m-%d %T')" >> $GITHUB_ENV

      - name: 提交更改
        run: |                 
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git pull origin master
          git add .
          git commit -m "${{env.REPORT_DATE}} 提交"
          git pull --rebase
          
      - name: Keepalive Workflow
        # You may pin to the exact commit or the version.
        # uses: gautamkrishnar/keepalive-workflow@1b33e4ef553c59eef0e3450666408021f4b0f456
        uses: gautamkrishnar/keepalive-workflow@1.0.9
        with:
          # GitHub access token with Repo scope
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: 推送更改
        uses:  ad-m/github-push-action@master
        with:
          branch: master
          github_token: ${{ secrets.GITHUB_TOKEN }}
